title: The Time Office
tags:
  - WordPress
  - TypeScript
  - Vue
  - Sass
description: Уютный коворкинг в городе Уфа
link: https://timeoffice.club
color: #E22B29
icon: ./images/icon.svg
screenshot: ./images/full-screenshot.png
cover: ./images/screenshot.png
