title: Simple Solution Group
tags:
  - Pug
  - Sass
description: Сайт гарантийного фонда Агентства Республики Башкортостан по предпринимательству
link: https://simple-solutions.group
color: #df1125
icon: ./images/icon.svg
screenshot: ./images/full-screenshot.png
cover: ./images/screenshot.png
