title: Гарантийный фонд
tags:
  - HTML
  - Sass
description: Сайт гарантийного фонда Агентства Республики Башкортостан по предпринимательству
link: https://gf-cmbrb.ru
color: #009FE1
icon: ./images/icon.svg
